### ISSUE TITLE
貌似对旋风有些漏检

### ISSUE THREAD

**Issue by wbsdty331** [chengr28/specialdlp#2]

**Comment by chengr28** [comment]
是否可提供一下对疑似客户端详细信息页面的截图？

**Comment by wbsdty331** [comment]
用的是最新的`44003 Update 2`
![qq 20160128222647](https://cloud.githubusercontent.com/assets/4280572/12647109/8bbecd4a-c60e-11e5-95c9-e086d11bb81f.jpg)

我会整理一下 过一段时间发所有可疑的客户端和用户HASH

**Comment by chengr28** [comment]
这还真是奇怪啊 `QQDownload` 本身是连官方版都屏蔽了的，看 UserHash 貌似也并没有上黑名单所以避过了官方版检测顺序的问题……反吸血插件的设置都是没有问题的？

**Comment by wbsdty331** [comment]
UserHash是正常的，偶尔会遇到一些下载的，`Xtreme`手动踢掉就好
我设置的是 社区客户端降分，`Bad ModString`和`Ghost MOD`都是直接封禁的
本来`eMule X Mod`是支持__不给吸血骡上传__功能的，但这个功能只有用官方DLP库才有效，使用其他第三方DLP（如`SDC`）之后，选项就会变为灰色不可选
![qq 20160128224000](https://cloud.githubusercontent.com/assets/4280572/12647427/149a6722-c610-11e5-933c-39a9806c008c.jpg)

**Comment by chengr28** [comment]
刚才仔细想了下 `QQDownload` 的检测是在硬性屏蔽列表里的，并不受这里选项的影响，也就是说这里选什么理论上都会彻底屏蔽掉 QQ 旋风，所以不太清楚是怎么回事……顺便说实话 X Mod 这个 `不要上传给吸血客户端` 使用非官方 DLP 时会被禁言其实针对的就是 SDC

**Comment by wbsdty331** [comment]
愿闻其详...

**Comment by chengr28** [comment]
我的意思是 `QQDownload` 那个我也不清楚是怎么回事……这边测试过并没有问题

**Comment by wbsdty331** [comment]
躺在床上，突然有个大胆的猜测
会不会是有人专门下了个0.48a的eMule，然后用户名改成`QQDownload`之流.....
2333333

**Comment by chengr28** [comment]
理论上是有可能的……所以就算是对某个 UserHash 进行屏蔽，都需要收集不少的数据
