### ISSUE TITLE
eMule v0.50a ZZUL-TRA 2.6 被不良的用户名这项检测到

### ISSUE THREAD

**Issue by javasboy** [chengr28/specialdlp#3]
我使用的 Xtreme 8.1 加载的 Strict DLP Chinese 44005 Update 1，会屏蔽正版 eMule v0.50a ZZUL-TRA 2.6，自动把IP加入到 IP 过滤里，日志如下：

`2017/3/21 10:48:10: Invalid packet with opcode: 0x1, size=149, data=[10 79 98 4c 6b 9f e 23 b d8 ba 94 98 f4 56 6f 6f fe bc 4a 0 6f 15 a 0 0 0 2 1 0 1 1c 0 7b 67 73 77 4d 7d 20 64 63 6c 6f 75 2d 77 65 62 2d..]; IP=xxx.xxx.xxx.xxxx
2017/3/21 10:48:10: IP: xxx.xxx.xxx.xxxx has been added temporary to the filtered list`

请测试。

**Comment by chengr28** [comment]
您好，希望能提供运行环境（操作系统）的信息，以及吸血客户端的屏蔽记录（选项 - 扩展设置 - 详情/额外的程序反馈 Verbose - 吸血客户端过滤记录选项）以便这边进行检查，谢谢。

**Comment by javasboy** [comment]
eMule V0.50a Xtreme 8.1 系统信息 DLP V44005-1 使用的是 x86\VeryCD-Tag\antiLeech.dll
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.14393 暂缺 Build 14393
系统类型:         x64-based PC


运行 eMule v0.50a ZZUL-TRA 2.6 的系统信息
OS 名称:          Microsoft Windows Server 2008 R2 Enterprise
OS 版本:          6.1.7600 暂缺 Build 7600
系统类型:         x64-based PC


在 eMule V0.50a Xtreme 8.1 中分享了一个文件，使用 eMule v0.50a ZZUL-TRA 2.6 下载


一个网友的请求下载在 Xtreme  Verbose 日志窗口中记录的信息如下：（实际IP被我替换了）
2017/3/24 10:14:59: A client has caused an undefined exception. Disconnecting client!
2017/3/24 10:14:59: Invalid packet with opcode: 0x1, size=144, data=[10 97 93 17 f0 2a e ff 3a 93 13 84 5 6f 69 6f 6d db 89 28 ed e f0 8 0 0 0 2 1 0 1 27 0 28 6b 6a 51 58 29 20 68 74 74 70 3a 2f 2f 65 6d 75..]; IP=8.8.8.8
2017/3/24 10:14:59: IP: 8.8.8.8 has been added temporary to the filtered list


我的 Server 2008 R2 eMule v0.50a ZZUL-TRA 2.6 low ID 下载在 Xtreme  Verbose 日志窗口中记录的信息：
2017/3/24 10:20:17: A client has caused an undefined exception. Disconnecting client!
2017/3/24 10:20:17: Invalid packet with opcode: 0x1, size=133, data=[10 79 98 4c 6b 9f e 23 b d8 ba 94 98 f4 56 6f 6f b4 c5 5e 0 6f 15 8 0 0 0 2 1 0 1 1c 0 28 67 73 77 4d 29 20 64 63 6c 6f 75 2d 77 65 62 2d..]; IP=4.4.4.4
2017/3/24 10:20:17: IP: 4.4.4.4 has been added temporary to the filtered list

以上在 Xtreme 的 吸血客户端过滤记录 里都没有日志，但是ZZ客户IP已经自动被 Xtreme 添加到 工具>IP过滤： 表述为 temporary，等级为 1的IP过滤表中了。

eMule v0.50a ZZUL-TRA 2.6 的 Verbose 日志窗口中没有相关记录。

**Comment by chengr28** [comment]
是这样的，这次应该算是一个 Bug……SDC 自己有一部分的高级过滤算法，因为一些逻辑上的问题导致 eMule 进行检测时抛出运行异常的错误，而因为有错误所以客户端无法成功通过反吸血插件的检测，进而 IP 地址被临时屏蔽。此类错误不会出现在过滤记录上，的确不太好发现……因应 eD2k 网络形势的变化，刚才更新的版本已经将此类高级过滤算法全部去掉了，感谢反馈。
