### ISSUE TITLE
这个是不是误报

### ISSUE THREAD

**Issue by 0x391F** [chengr28/specialdlp#5]
![1](https://user-images.githubusercontent.com/56181919/129294698-b205e6fe-22ff-4dbe-9c43-5e4ca8e77345.png)

**Comment by 0x391F** [comment]
[ModString Thief](reduce score)- Client 4298978@5.45.85.226 (27.195.72.146) 'ScarAngel @ http://scarangel.sourceforge.net «[Xve?]»' (eMule v0.50a [ScarAngel 4.2],None/None/BuddyIncoming)

**Comment by chengr28** [comment]
这个不是误报，真正的 ScarAngel 用户名格式是类似 `xxx [xxxx] «ScarAngel *.*»` 这样的。
