### ISSUE TITLE
X Mod 1.6.1加载x64版卡死

### ISSUE THREAD

**Issue by Xenon-Q** [chengr28/specialdlp#6]
试过easymule版和verycd-tag版，都有这个问题
操作系统为Windows 10 LTSC 2021

**Comment by chengr28** [comment]
想到了几个可能性，但是不确定是启用了哪个特性的原因。
先问一下你的 CPU 是否带有 AVX 指令集？

**Comment by Xenon-Q** [comment]
> 

确实，那台电脑初代I7平台，i7-940XM
换了台九代平台i9-9980HK使用正常

**Comment by Xenon-Q** [comment]
> 想到了几个可能性，但是不确定是启用了哪个特性的原因。 先问一下你的 CPU 是否带有 AVX 指令集？

确实，那台电脑初代I7平台，i7-940XM
换了台九代平台i9-9980HK使用正常

**Comment by chengr28** [comment]
我看看出一个降级到 SSE2 的 hotfix 的 release，如果测试没有问题到时候再发一个新的版本。
Update 10 开始才要求 AVX 指令集，现在看还是有不少的机器没有 AVX 这样看还是退回 SSE2 比较好。

**Comment by chengr28** [comment]
[Hotfix 的版本](https://github.com/chengr28/specialdlp/releases/tag/v44005.10)已经附加到 Update 10 的 release 里，如果没有问题下一个正式版本将会转为 Hotfix 的编译参数。
