### ISSUE TITLE
emule0.50a-Xtreme8.1无法加载update10每个版本

### ISSUE THREAD

**Issue by IOPSL** [chengr28/specialdlp#7]
CPU为常见低功耗的J4125、操作系统为Windows 10 LTSC，emule日志框reload报ErrorCode: 0、冷启动报ErrorCode: 193

可能是AVX的问题，另外较新的低功耗CPU如N100在ARK中标识支持AVX2，亦不知能否兼容AVX，可否考虑指令集至SSE

**Comment by chengr28** [comment]
[Does a Processor with AVX2 or AVX-512 Support AVX Instructions?](https://www.intel.com/content/www/us/en/support/articles/000058796/processors.html)
实际上有标明 AVX2 或者 AVX-512 的 CPU 都是向后兼容 AVX 的。

我看看出一个降级到 SSE2 的 hotfix 的 release，如果测试没有问题到时候再发一个新的版本。

**Comment by IOPSL** [comment]
Clone了master尝试用VS2022编译第一个X86版本，除了调整指令集外为“未设置”还将MFC链接改为“静态”，当前配置能够载入成功但尚未长时间运行验证，期待official release

**Comment by chengr28** [comment]
[Hotfix 的版本](https://github.com/chengr28/specialdlp/releases/tag/v44005.10)已经附加到 Update 10 的 release 里，如果没有问题下一个正式版本将会转为 Hotfix 的编译参数。
